/**
 * A lazy value generated by a given 'generate' function. It is evaluated once when its value is first requested and
 * memoized afterwards.
 */
export class LazyValue<V> {
  generate: () => V
  _value: V | undefined

  constructor(generate: () => V) {
    this.generate = generate
    this._value = undefined
  }

  value() {
    if (this._value) {
      return this._value
    }
    this._value = this.generate()
    return this._value
  }
}
